### ISSUE TITLE
Commands::AddDevices Error: RuntimeError

### ISSUE THREAD

**Issue by lulurun** [DeployGate/deploygate-cli#155]
# Status
deploygate-cli ver 0.4.1

# Error message
Invalid 2 step response {"trustedPhoneNumbers"=>[{"verified"=>true, "obfuscatedNumber"=>"••••••••26", "rawNumber"=>"********26", "id"=>1, "countryCode"=>"JP", "numberWithDialCode"=>"+81 ••••••••26", "countryDialCode"=>"81", "createDate"=>"07/02/2016 01:25:57 AM", "updateDate"=>"07/02/2016 01:25:57 AM", "number"=>"********26", "pushMode"=>"sms", "pending"=>false, "lastTwoDigits"=>"26"}], "securityCode"=>{"length"=>6, "tooManyCodesSent"=>false, "tooManyCodesValidated"=>false, "securityCodeLocked"=>false}, "authenticationType"=>"hsa2", "recoveryUrl"=>"https://iforgot.apple.com/phone/add?prs_account_nm=lulurun@gmail.com&autoSubmitAccount=true&appId=142", "cantUsePhoneNumberUrl"=>"https://iforgot.apple.com/iforgot/phone/add?context=cantuse&prs_account_nm=lulurun@gmail.com&autoSubmitAccount=true&appId=142", "recoveryWebUrl"=>"https://iforgot.apple.com/password/verify/appleid?prs_account_nm=lulurun@gmail.com&autoSubmitAccount=true&appId=142", "repairPhoneNumberUrl"=>"https://gsa.apple.com/appleid/account/manage/repair/verify/phone", "repairPhoneNumberWebUrl"=>"https://appleid.apple.com/widget/account/?#!repair", "aboutTwoFactorAuthenticationUrl"=>"https://support.apple.com/kb/HT204921", "trustedPhoneNumber"=>{"verified"=>true, "obfuscatedNumber"=>"••••••••26", "rawNumber"=>"********26", "id"=>1, "countryCode"=>"JP", "numberWithDialCode"=>"+81 ••••••••26", "countryDialCode"=>"81", "createDate"=>"07/02/2016 01:25:57 AM", "updateDate"=>"07/02/2016 01:25:57 AM", "number"=>"********26", "pushMode"=>"sms", "pending"=>false, "lastTwoDigits"=>"26"}, "hsa2Account"=>true, "supportsRecovery"=>true, "managedAccount"=>false}

# Backtrace
```
/usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.32.4/lib/spaceship/two_step_client.rb:42:in `handle_two_step'
/usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.32.4/lib/spaceship/client.rb:298:in `send_shared_login_request'
/usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.32.4/lib/spaceship/portal/portal_client.rb:13:in `send_login_request'
/usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.32.4/lib/spaceship/client.rb:370:in `do_login'
/usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.32.4/lib/spaceship/client.rb:227:in `login'
/usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.32.4/lib/spaceship/launcher.rb:25:in `initialize'
/usr/local/lib/ruby/gems/2.2.0/gems/deploygate-0.4.1/lib/deploygate/xcode/member_center.rb:11:in `new'
/usr/local/lib/ruby/gems/2.2.0/gems/deploygate-0.4.1/lib/deploygate/xcode/member_center.rb:11:in `initialize'
/usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/singleton.rb:141:in `new'
/usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/singleton.rb:141:in `block in instance'
/usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/singleton.rb:139:in `synchronize'
/usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/singleton.rb:139:in `instance'
/usr/local/lib/ruby/gems/2.2.0/gems/deploygate-0.4.1/lib/deploygate/xcode/member_centers/device.rb:27:in `register!'
/usr/local/lib/ruby/gems/2.2.0/gems/deploygate-0.4.1/lib/deploygate/commands/add_devices.rb:62:in `block in register!'
/usr/local/lib/ruby/gems/2.2.0/gems/deploygate-0.4.1/lib/deploygate/commands/add_devices.rb:61:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/deploygate-0.4.1/lib/deploygate/commands/add_devices.rb:61:in `register!'
/usr/local/lib/ruby/gems/2.2.0/gems/deploygate-0.4.1/lib/deploygate/commands/add_devices.rb:43:in `device_register'
/usr/local/lib/ruby/gems/2.2.0/gems/deploygate-0.4.1/lib/deploygate/commands/add_devices.rb:29:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/deploygate-0.4.1/lib/deploygate/command_builder.rb:88:in `block (2 levels) in run'
/usr/local/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane_core-0.52.1/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
/usr/local/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
/usr/local/lib/ruby/gems/2.2.0/gems/deploygate-0.4.1/lib/deploygate/command_builder.rb:125:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/deploygate-0.4.1/bin/dg:6:in `<top (required)>'
/usr/local/bin/dg:23:in `load'
/usr/local/bin/dg:23:in `<main>'
```

**Comment by henteko** [comment]
Thank you feedback!
Released a new version so please try it.
https://rubygems.org/gems/deploygate/versions/0.5.0
