### ISSUE TITLE
How do I specify a workspace/project when multiple xcworkspeces/xcprojects are there in the project directory

### ISSUE THREAD

**Issue by skonb** [DeployGate/deploygate-cli#169]
Hi,

it seems to automatically select a xcworkspace if multiple ones are there, can I specify it as fastlane gym do?
Thanks in advance.

**Comment by henteko** [comment]
Sorry, deploygate-cli does not support multiple xcworkspace.
I created an issue!
#171 

Thanks!

**Comment by skonb** [comment]
@henteko Thanks!
