### ISSUE TITLE
'to_sym' error when I try. to run dg deploy

### ISSUE THREAD

**Issue by IsseTommy** [DeployGate/deploygate-cli#291]
I got this error when I try to run dg deploy on my iOS project.
Could you please tell me how can I fix this problem...?

```:
Error: undefined method `to_sym' for nil:NilClass

------------------------
DeployGate Error Report 

Title: undefined method `to_sym' for nil:NilClass
dg version: 0.8.3
Xcode version: 12.2

Stack trace:
/Library/Ruby/Gems/2.6.0/gems/deploygate-0.8.3/lib/deploygate/xcode/analyze.rb:88:in `target_provisioning_profile'
/Library/Ruby/Gems/2.6.0/gems/deploygate-0.8.3/lib/deploygate/commands/deploy/build.rb:49:in `ios'
/Library/Ruby/Gems/2.6.0/gems/deploygate-0.8.3/lib/deploygate/commands/deploy/build.rb:22:in `run'
/Library/Ruby/Gems/2.6.0/gems/deploygate-0.8.3/lib/deploygate/commands/deploy.rb:16:in `run'
/Library/Ruby/Gems/2.6.0/gems/deploygate-0.8.3/lib/deploygate/command_builder.rb:76:in `block (2 levels) in run'
and more ...
------------------------
```

**Comment by khanhbk08t1** [comment]
Can u tell me know what is fix this bug?

**Comment by d-nakajima** [comment]
I faced this issue. Try `--configuration` option and set value what you want to use.
If you don't set this command, the `Release` configuration seems to be used.   
(The default is defined on https://github.com/DeployGate/deploygate-cli/blob/9fc5bfca02fbdd2b4807770527b563959702c0de/lib/deploygate/xcode/analyze.rb#L7C7-L7C46 ) and I cannot find override it without above option.  )  

I hope this will be of some help :)
