### ISSUE TITLE
Runtime dependencies are too old or too many unnecessarily

### ISSUE THREAD

**Issue by ainame** [DeployGate/deploygate-cli#294]
I realised that `fastlane` and `deploygate` gems can't really coexist with a Gemfile env. When I tried the below Gemfile, `bundle install` resulted in installing a very old `fasltnae` gem, which is v1.92.0. The latest version of `fastlane` is now 2.199.0 so it's stale and I guess nothing would work as expected. 

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "fastlane"
gem "deploygate"
```

If I specify each gem's latest version, like below, this also ends up failing. 

```ruby
gem "fastlane", ">= 2.199.0"
gem "deploygate", ">= 0.8.3"
```

This constraint is too strict as we can't update `fasltane` to the latest version. It's still impossible to install this gem with Ruby 3  since fastlane `2.148.1` didn't support it officially yet #292 
https://github.com/DeployGate/deploygate-cli/blob/93db3e55f25ddcb348cf928d7c9c95989639f2ee/deploygate.gemspec#L41

Looking at the gemspec, I can see some other points.

* `activesupport` is too old and ideally we shouldn't use it in non-rails applications😂
   * `xcodeproj` no longer depends on it
* `commander` and `highline` remains old though it's easy to migrate to the latest versions 
   * Given its dependency `fastlane` also heavily relies on them, this gem should not be strict about versioning on them
* `sentry-raven` is in maintenance mode (no longer actively developed)  https://rubygems.org/gems/sentry-raven

People would be able to upload ipa/apk files via `deploygate` **action** in `Fastfile` that doesn't rely on `deploygate` **gem** but it's still great to see both gems are bundled and can use `dg` command directly and seamlessly.

**Comment by henteko** [comment]
@ainame 
Thanks for pointing out the details!
But, the dg command will be closed in the future.
We will be announce people to use fastlane deploygate action instead.

**Comment by ainame** [comment]
Got it. Thank you!
