### ISSUE TITLE
[ERROR] undefined method `exists?' for class File

### ISSUE THREAD

**Issue by fnaoto** [DeployGate/deploygate-cli#324]
When above ruby 3.2, `exists?` is undefined for class File.

https://github.com/DeployGate/deploygate-cli/blob/2b98ea11133b0aa303fbe185a2b8a4e51c69dc10/lib/deploygate/android/gradle_project.rb#L9

ruby 3.1
- https://docs.ruby-lang.org/ja/3.1/method/File/s/exists=3f.html

issues
- https://www.reddit.com/r/ruby/comments/1196wti/psa_and_a_little_rant_fileexists_direxists/

**Comment by jmatsu** [comment]
Closed by #325
