### ISSUE TITLE
Commands::Deploy Error: Spaceship::Client::UnexpectedResponse

### ISSUE THREAD

**Issue by m0a** [DeployGate/deploygate-cli#89]
# Status
deploygate-cli ver 0.2.0

# Error message
Couldn't download provisioning profile, got this instead: <!DOCTYPE html>
<html>
<head>
	<title>Page Not Found - Apple Developer</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="omni_page" content="404:/account/ios/profile/profileContentDownload.action" />
	<link rel="stylesheet" href="https://www.apple.com/wss/fonts?family=Myriad+Set+Pro&v=1" type="text/css" />
	<link rel="stylesheet" href="https://devimages.apple.com.edgekey.net/assets/styles/systems.css" type="text/css" />
	<script src="/pagenotfound/scripts/pnf.js"></script>
	
</head>
<body class="pnf">
	<div id="top">

<script type="text/javascript">
/* RSID: */
var s_account="appleglobal,appleusdeveloper"
</script>

<script type="text/javascript" src="https://www.apple.com/metrics/scripts/s_code_h.js"></script>
<script type="text/javascript">
s.channel="www.us.developer"
s.pageType="errorPage"

/************* DO NOT ALTER ANYTHING BELOW THIS LINE ! **************/
var s_code=s.t();if(s_code)document.write(s_code)</script>

</div>	<section class="wrapper">
	<section id="content" class="content">
		<header class="header">
			<h1><a href="https://developer.apple.com/"><span class="text-replace">Apple Developer</span></a></h1>
		</header>

		<h2>Sorry, that page cannot be found.</h2>
		<p>Try searching below or go to <a href="http://developer.apple.com">developer.apple.com</a>.</p>
		<form method="get" action="/search/"  name="searchform">
			<input class="search-field" id="search" type="text" placeholder="Search" name="q" value="" onkeydown="if (event.keyCode == 13) document.searchform.submit()" />
			<span class="search-field-mag"></span>
			<input type="submit" id="submit" class="offscreen" />
		</form>

	</section>

	<aside class="push"></aside>
</section>

<footer class="footer">
	<nav class="sosumi">
		<p>Copyright © 2015 Apple Inc. All rights reserved.</p>
		<ul class="links">
			<li><a href="http://www.apple.com/legal/terms/site.html" class="first">Terms of Use</a></li>
			<li><a href="http://www.apple.com/privacy/">Privacy Policy</a></li>
			<li><a href="http://developer.apple.com/support/system-status/">System Status</a></li>
		</ul>
	</nav>
</footer>
</body>
</html>

# Backtrace
```
/usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.19.4/lib/spaceship/portal/portal_client.rb:375:in `download_provisioning_profile'
/usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.19.4/lib/spaceship/portal/provisioning_profile.rb:304:in `download'
/usr/local/lib/ruby/gems/2.3.0/gems/sigh-1.2.2/lib/sigh/runner.rb:170:in `block in download_profile'
/usr/local/lib/ruby/gems/2.3.0/gems/sigh-1.2.2/lib/sigh/runner.rb:169:in `open'
/usr/local/lib/ruby/gems/2.3.0/gems/sigh-1.2.2/lib/sigh/runner.rb:169:in `download_profile'
/usr/local/lib/ruby/gems/2.3.0/gems/sigh-1.2.2/lib/sigh/runner.rb:50:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/sigh-1.2.2/lib/sigh/manager.rb:7:in `start'
/usr/local/lib/ruby/gems/2.3.0/gems/deploygate-0.2.0/lib/deploygate/xcode/member_centers/provisioning_profile.rb:84:in `download_profile'
/usr/local/lib/ruby/gems/2.3.0/gems/deploygate-0.2.0/lib/deploygate/xcode/member_centers/provisioning_profile.rb:75:in `download'
/usr/local/lib/ruby/gems/2.3.0/gems/deploygate-0.2.0/lib/deploygate/xcode/member_centers/provisioning_profile.rb:28:in `create!'
/usr/local/lib/ruby/gems/2.3.0/gems/deploygate-0.2.0/lib/deploygate/xcode/export.rb:215:in `create_provisioning'
/usr/local/lib/ruby/gems/2.3.0/gems/deploygate-0.2.0/lib/deploygate/xcode/export.rb:20:in `provisioning_profile'
/usr/local/lib/ruby/gems/2.3.0/gems/deploygate-0.2.0/lib/deploygate/commands/deploy/build.rb:36:in `ios'
/usr/local/lib/ruby/gems/2.3.0/gems/deploygate-0.2.0/lib/deploygate/commands/deploy/build.rb:17:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/deploygate-0.2.0/lib/deploygate/commands/deploy.rb:16:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/deploygate-0.2.0/lib/deploygate/command_builder.rb:51:in `block (2 levels) in run'
/usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
/usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.37.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
/usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
/usr/local/lib/ruby/gems/2.3.0/gems/deploygate-0.2.0/lib/deploygate/command_builder.rb:106:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/deploygate-0.2.0/bin/dg:6:in `<top (required)>'
/usr/local/bin/dg:22:in `load'
/usr/local/bin/dg:22:in `<main>'
```

**Comment by henteko** [comment]
Thanks for your report!

**Comment by henteko** [comment]
@m0a 
ありがとうございます！
新しいversionを作ってみたので、こちらで試していただけませんか？
https://deploygate.s3.amazonaws.com/clients/deploygate-0.2.1.pre.gem

gemファイルをダウンロードして、以下のようにコマンドを叩くとインストールできます

```
$ gem install deploygate-0.2.1.pre.gem
```

インストール後、versionが0.2.1.preになっていることをご確認ください

```
$ dg version
```

**Comment by henteko** [comment]
このissueは [v0.2.1](https://rubygems.org/gems/deploygate/versions/0.2.1) で解決したと思うのでcloseします！
